### ISSUE TITLE
Use MAUI events

### ISSUE THREAD

**Issue by tranb3r** [FabriBertani/Plugin.Maui.ScreenSecurity#3]
Hi,
I think it would be nice to be able to call this plugin when configuring MAUI app events (MauiAppBuilder.ConfigureLifecycleEvents).
The problem is that iOS methods are already using events, and private methods are (by definition) not accessible.
Maybe there is something I'm not doing correctly?
Thanks

```
public static MauiAppBuilder ConfigureMaui(this MauiAppBuilder builder)
{
    builder.ConfigureLifecycleEvents(events =>
    {
        events.AddiOS(iOS => iOS.DidEnterBackground(app =>
        {
            ScreenSecurity.Default.EnableBlurScreen(ThemeStyle.Light); // EnableBlurScreen is private
        }));
        events.AddiOS(iOS => iOS.WillEnterForeground(app =>
        {
            ScreenSecurity.Default.DisableBlurScreen(); // DisableBlurScreen is private
        }));
    });
    return builder;
}
```

**Comment by FabriBertani** [comment]
Hi @tranb3r and thank you for bringing this up.

You can completely use the `ConfigureLifecycleEvents` with the current state of the plugin, without needing to access the private methods.
In your case, it's not working because you're calling the wrong iOS events, the correct implementation would be:

```csharp
public static class MauiProgram
{
    public static MauiApp CreateMauiApp()
    {
        var builder = MauiApp.CreateBuilder();
        builder
            .UseMauiApp<App>()
            .ConfigureLifecycleEvents(events =>
            {
                events.AddiOS(iOS =>
                {
                    iOS.OnResignActivation(app =>
                    {
                        ScreenSecurity.Default.EnableBlurScreenProtection(ThemeStyle.Light);
                    });

                    iOS.OnActivated(app =>
                    {
                        ScreenSecurity.Default.DisableBlurScreenProtection();
                    });
                });
            });

        return builder.Build();
    }
}
```

In this particular case, the screen protector will be applied to the entire application from the beginning and for the entire application life cycle.

By allowing users to inject the interface and apply any of the methods available, they can handle the execution at any time in the life cycle or to any particular screen they want to secure.

Hope this clarifies your question.

**Comment by tranb3r** [comment]
I totally understand the DI stuff and why it could be important to protect only a specific screen.
And you're right, I my scenario, I'd like the screen protector to be applied to the entire application, for the entire life cycle.

However, can you explain why we need to register for the event twice, first in ConfigureLifecycleEvents (iOS.OnResignActivation) and then in EnableBlurScreenProtection (UIApplication.Notifications.ObserveWillResignActive)? 
It seems weird to me, having to call ObserveWillResignActive in ConfigureLifecyleEvents, and not being able to call directly EnableBlurScreen.

**Comment by FabriBertani** [comment]
I'm just answering your question about how to register using the `ConfigureLifecycleEvents`, it's the best option? Of course not, because the plugin itself attaches to those events internally [as you can see here](https://github.com/FabriBertani/Plugin.Maui.ScreenSecurity/blob/main/Plugin.Maui.ScreenSecurity/Platforms/iOS/ScreenSecurity.ios.cs#L26).

The idea of this plugin is to relieve the user from having to do all the implementation by themselves.
On the other hand, exposing the internal implementation of these methods wouldn't be safe.

If you want to protect your application from the beginning and for the rest of the application lifecycle, you can use the interface or default implementation and call the method you like on your first ViewModel or the code behind of your first screen.

**Comment by tranb3r** [comment]
You're right, there is no need to expose private methods, the plugin already attaches to the correct events.
Thank you for the clarification.
