### ISSUE TITLE
Keyboard is still appearing  during recording

### ISSUE THREAD

**Issue by CalbinKing** [FabriBertani/Plugin.Maui.ScreenSecurity#37]
I'm using 1.1.7-bete Both iOS and Android still show the keyboard during recording

```
        /// <summary>
        ///     When overridden, allows application developers to customize behavior immediately prior to the
        ///     <see cref="Page" /> becoming visible.
        /// </summary>
        protected override void OnAppearing()
        {
            ScreenSecurity.Default.ActivateScreenSecurityProtection();
            base.OnAppearing();      
        }

        /// <summary>
        ///     When overridden, allows the application developer to customize behavior as the <see cref="Page" />
        ///     disappears.
        /// </summary>
        protected override void OnDisappearing()
        {
            ScreenSecurity.Default.DeactivateScreenSecurityProtection();
            base.OnDisappearing();
        }
```
![20240805_085254000_iOS](https://github.com/user-attachments/assets/f28f7e7a-f5bc-4f92-8f7c-fc13a3d14192).
![20240805_085305000_iOS](https://github.c
![Screenshot_20240805_150311_com huawei himovie overseas](https://github.com/user-attachments/assets/39ca665c-f6b5-40ed-800c-88f4b0b7a505)
om/user-attachments/assets/1f5873d8-53d3-4e9c-b8a1-dc71244b60df)
![Screenshot_20240805_150234_com huawei himovie overseas](https://github.com/user-attachments/assets/c5e21f85-21d1-4689-9016-7fbb6bbf7af3)

**Comment by FabriBertani** [comment]
Hi @CalbinKing , hope you're doing well.

Unfortunately, this is impossible to archive because the keyboard and other stuff are OS related and we cannot control them. The only way to hide the keyboard from recording and screenshots is by setting `IsPassword` property of an `Entry` control to `true`, Apple designed it to be this way.

Best I can do is create an `EventHandler` only for iOS, that is triggered when recording starts/ends and you can see how to handle the situation.

Let me know if that will work for you.

**Comment by FabriBertani** [comment]
I've added an event handler to check if a screenshot was taken or a screen recording is happening, feel free to check the latest version, maybe you can react to it and make some implementation to hide or disable the keyboard.
